-- ================================================================
-- SQL DDL TEMPLATE (TOPIC 04)
-- ================================================================
-- WHAT SHOULD BE ADDED HERE:
-- 1) Full PostgreSQL DDL for your finalized schema.
-- 2) CREATE TABLE statements for all entities from your ER diagram.
-- 3) Primary keys, foreign keys, NOT NULL, UNIQUE, CHECK constraints.
-- 4) Indexes for important search/join columns.
-- 5) Clean structure and comments (group by tables/constraints/indexes).
--
-- RECOMMENDED ORDER:
-- 1) Tables
-- 2) Constraints (if not inline)
-- 3) Indexes
--
-- TEAM NOTE:
-- Add short attribution comments for who implemented which part.
-- Example:
-- [Name] - users, roles, permissions tables
-- [Name] - orders, payments, invoices tables
--
-- IMPORTANT:
-- The script must run in PostgreSQL and produce a working schema that
-- matches your approved ER diagram and conceptual schema.
-- Submit this as one SQL file.
-- ================================================================

-- Add your DDL below this line

drop table if exists location_inventory; 
drop table if exists supplier_ingredients; 
drop table if exists suppliers; 
drop table if exists shift_schedules; 
drop table if exists staff; 
drop table if exists order_items; 
drop table if exists customer_feedback; 
drop table if exists reservations; 
drop table if exists restaurant_tables; 
drop table if exists orders; 
drop table if exists customers; 
drop table if exists menu_item_ingredients; 
drop table if exists locations; 
drop table if exists ingredients;
drop table if exists menu_items; 
drop table if exists menu_categories; 

drop type if exists shift_status;
drop type if exists order_status;
drop type if exists order_type;


/*******************************************************************
Vitaliy Fronts Simple inventory tracking, Basic restaurant location management
*******************************************************************/
CREATE TABLE locations (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  address varchar(255) NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE location_inventory (
  location_id bigint NOT NULL,
  ingredient_id bigint NOT NULL,
  current_stock numeric(12,3) NOT NULL CHECK (current_stock >= 0) DEFAULT 0,
  min_stock_level numeric(12,3) NOT NULL CHECK (min_stock_level >= 0) DEFAULT 0,
  
  PRIMARY KEY (location_id, ingredient_id),
  FOREIGN KEY (location_id) REFERENCES locations (location_id)
);

CREATE TABLE suppliers (
  supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(150) NOT NULL,
  phone varchar(30),
  email varchar(150),
  address varchar(255)
);

CREATE TABLE supplier_ingredients (
  supplier_id bigint NOT NULL,
  ingredient_id bigint NOT NULL,
  purchase_price numeric(10,2) NOT NULL CHECK (purchase_price >= 0),
  effective_date date NOT NULL DEFAULT (current_date),
  PRIMARY KEY (supplier_id, ingredient_id, effective_date)
);

CREATE INDEX ON location_inventory (ingredient_id);
CREATE INDEX ON supplier_ingredients (ingredient_id);

/*******************************************************************
Maksym Soloviov Menu items and categories
*******************************************************************/

CREATE TABLE menu_categories (
  category_id bigint PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  description varchar(50) NOT NULL
);

CREATE TABLE  menu_items (
  menu_item_id bigint,
  category_id bigint,
  name varchar(50) NOT NULL UNIQUE,
  price decimal(8,2) NOT NULL,
  preparation_time_min smallint NOT NULL,
  is_available boolean NOT NULL,

  PRIMARY KEY(menu_item_id),
  FOREIGN KEY(category_id) references menu_categories(category_id)
);

CREATE TABLE ingredients (
  ingredient_id bigint PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  unit varchar(50) NOT NULL
);

CREATE TABLE menu_item_ingredients (
  menu_item_id bigint,
  ingredient_id bigint,
  quantity_demand decimal(10,3) CHECK (quantity_demand > 0) NOT NULL,

  PRIMARY KEY(menu_item_id, ingredient_id),
  FOREIGN KEY(menu_item_id) REFERENCES menu_items (menu_item_id),
  FOREIGN KEY(ingredient_id) REFERENCES ingredients (ingredient_id)
);

CREATE INDEX ON menu_items (category_id);
CREATE INDEX ON menu_item_ingredients (ingredient_id);


/*******************************************************************
 Valerii Kyrpychenko - staff management and shift scheduling tables
********************************************************************/

CREATE TABLE staff (
    staff_id bigserial PRIMARY KEY,
    location_id bigint NOT NULL REFERENCES locations (location_id),
    first_name varchar(80) NOT NULL,
    last_name varchar(80) NOT NULL,
    middle_name varchar(80),
    birth_date date NOT NULL,
    position varchar(30) NOT NULL,
    phone varchar(30) NOT NULL UNIQUE,
    email varchar(150) NOT NULL UNIQUE,
    is_active boolean DEFAULT TRUE
);

CREATE INDEX idx_staff_location ON staff (location_id);
CREATE INDEX idx_staff_name_birth ON staff (last_name, first_name, birth_date);

CREATE TYPE shift_status AS ENUM (
  'SCHEDULED',
  'IN_PROGRESS',
  'COMPLETED',
  'NO_SHOW',
  'CANCELLED');

CREATE TABLE shift_schedules (
    shift_id bigserial PRIMARY KEY,
    location_id bigint NOT NULL REFERENCES locations (location_id),
    staff_id bigint NOT NULL REFERENCES staff (staff_id),
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    actual_start_time timestamptz,
    actual_end_time timestamptz,
    break_time_minutes smallint DEFAULT 0 CHECK (break_time_minutes >= 0),
    status shift_status NOT NULL DEFAULT 'SCHEDULED',

    CONSTRAINT chk_shift_time 
    CHECK (end_time > start_time),

    CONSTRAINT chk_actual_time_consistency
    CHECK ((actual_end_time IS NULL OR actual_start_time IS NOT NULL)
    AND (actual_end_time > actual_start_time) ),

    CONSTRAINT uq_shift_staff_slot
    UNIQUE (staff_id, start_time)
);

CREATE INDEX idx_shift_staff ON shift_schedules (staff_id);
CREATE INDEX idx_shift_location ON shift_schedules (location_id);
CREATE INDEX idx_shift_date ON shift_schedules (start_time);
CREATE INDEX idx_shift_location_date ON shift_schedules (location_id, start_time);

/*******************************************************************
 Oleksii Antypov - Basic order processing
********************************************************************/

CREATE TYPE order_status AS ENUM (
  'NEW',
  'PREPARING',
  'READY',
  'COMPLETED',
  'CANCELLED'
);

CREATE TYPE order_type AS ENUM (
  'DINE_IN',
  'TAKEAWAY'
);

CREATE TABLE customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(80) NOT NULL,
  last_name varchar(80),
  phone varchar(30),
  email varchar(150)
);

CREATE TABLE orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number bigint NOT NULL,
  location_id bigint NOT NULL,
  customer_id bigint NOT NULL,
  order_type order_type NOT NULL DEFAULT 'DINE_IN',
  status order_status NOT NULL DEFAULT 'NEW',
  ordered_at timestamptz NOT NULL DEFAULT (now()),
  total_order_amount numeric(10,2) NOT NULL CHECK (total_order_amount >= 0) DEFAULT 0,

  FOREIGN KEY(location_id) REFERENCES locations (location_id),
  FOREIGN KEY(customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE order_items (
  order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  menu_item_id bigint NOT NULL,
  quantity int NOT NULL CHECK (quantity > 0),
  item_price numeric(10,2) NOT NULL CHECK (item_price >= 0),

  FOREIGN KEY(order_id) REFERENCES orders (order_id),
  FOREIGN KEY(menu_item_id) REFERENCES menu_items (menu_item_id)
);

CREATE TABLE customer_feedback (
  feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL,
  location_id bigint NOT NULL,
  order_id bigint,
  rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment text,
  created_at timestamptz NOT NULL DEFAULT (now()),

  FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
  FOREIGN KEY (location_id) REFERENCES locations (location_id),
  FOREIGN KEY (order_id) REFERENCES orders (order_id)
);

CREATE TABLE restaurant_tables (
  location_id bigint NOT NULL,
  table_number varchar(10) NOT NULL,
  seats_count smallint NOT NULL CHECK (seats_count > 0),
  PRIMARY KEY (location_id, table_number),

  FOREIGN KEY (location_id) REFERENCES locations (location_id)
);

CREATE TABLE reservations (
  reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id bigint NOT NULL,
  customer_id bigint NOT NULL,
  table_number varchar(10) NOT NULL,
  reservation_datetime timestamptz NOT NULL,
  guests_count smallint NOT NULL CHECK (guests_count > 0),
  status varchar(20) NOT NULL,

  FOREIGN KEY (location_id) REFERENCES locations (location_id),
  FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
  FOREIGN KEY (location_id, table_number) REFERENCES restaurant_tables (location_id, table_number)
);

CREATE UNIQUE INDEX ON orders (location_id, order_number);
CREATE INDEX ON orders (location_id);
CREATE INDEX ON orders (customer_id);
CREATE INDEX ON order_items (order_id);
CREATE INDEX ON order_items (menu_item_id);
CREATE UNIQUE INDEX ON customers (email);
CREATE INDEX ON customer_feedback (customer_id);
CREATE INDEX ON customer_feedback (location_id);
CREATE INDEX ON customer_feedback (order_id);
CREATE UNIQUE INDEX ON reservations (location_id, table_number, reservation_datetime);
CREATE INDEX ON reservations (customer_id);

COMMENT ON COLUMN customers.first_name IS 'For anonymous orders, use a predefined Anonymous customer record';
COMMENT ON COLUMN orders.customer_id IS 'References a registered customer or a predefined Anonymous customer record';

----
ALTER TABLE location_inventory ADD FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id);
ALTER TABLE location_inventory ADD FOREIGN KEY (location_id) REFERENCES locations (location_id);
ALTER TABLE supplier_ingredients ADD FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id);
ALTER TABLE supplier_ingredients ADD FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id);

